name: Simple Push Check

on: [push]

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello form Github Actions! The workflow has run"
      - name: List Files
        run: ls -la
